### ISSUE TITLE
Get url from view

### ISSUE THREAD

**Issue by wielski** [UniSharp/laravel-fileapi#2]
I have assigned alias for FileApi class in app.php

        'File'      => Unisharp\FileApi\FileApi::class,

When I try to use it in blade view i got error

        Non-static method Unisharp\FileApi\FileApi::get() should not be called statically, assuming $this from incompatible context (View: /Users/wielski/Documents/MAMP/shop.dev/resources/views/admin/users/list.blade.php)

Please make static function for using in Blade, like

        {{ File::get($user->avatar, 'S') or '/images/avatars/default.png' }}

**Comment by wielski** [comment]
I have to write custom function in helpers.php

    use \Unisharp\FileApi\FileApi;
    function getFile($name, $size = 'L', $path = 'images/', $cloud = false){
      $fa = new FileApi($path);
      if($fa->getUrl($name, $size) == $path) return false;
      return $fa->get($name, $size);
     }

Using like this:

     {{ (getFile($user->avatar, 'S', 'images/avatars/')) ? getFile($user->avatar, 'S', 'images/avatars/') : 'images/avatars/default.png' }}

Very poor solution, but it working.
getUrl always return only path, if file not found.

And, local storage path is olways without / (images/avatar/file.png instead /images/avatar/file.php)
It's not good to.

**Comment by FreedomKnight** [comment]
Hi, @wielski
we don't use alias because we want to let it change image path more flexible.
so we let developer setting path in initial time.

We will consider your opinion.

**Comment by g0110280** [comment]
Hello @wielski ,
We suggest you use FileApi like below :
![2015-12-29 10 57 22](https://cloud.githubusercontent.com/assets/7333171/12028961/33e58ed4-ae1b-11e5-99ae-72f0fbb0f8c4.png)

Create your helper function in your User model, dealing with FileApi and default image.
So in blade you can just use the code below :
```php
{{ $user->avatarImage() }}
```
And you will get exactly what you want.
Hope this helps you.
